- name: nginx
  hosts: ansible
  become: yes
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Run nginx servicee
    ansible.builtin.service:
      name: nginx
      service: started
