- name: PLAY 1
  hosts: local
  connection: local
  tasks:
  - name: PLAY 1 AND TASK1
    ansible.builtin.debug:
      msg: "Hello from PLAY 1 AND TASK 1"

- name: PLAY 2 
  hosts: local
  connection: local
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run nginx service
    ansible.builtin.service:
      name: nginx
      state: started