- name: run the variables
  hosts: local
  connection: local
  vars:
    COURSE: "devops with aws"
    DURATION: 120hrs
    TRAINER: "siva kumar"
  
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "course is {{COURSE}}, duration is {{DURATION}}, trainer is {{TRAINER}}"
    
  - name: "print the variables 1"
    ansible.builtin.debug:
      msg: "course is ansible, duration is 100hrs, trainer is siva anna"