- name: prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: enter your course name
  - name: DURATION
    prompt: enter your duration
  - name: TRAINER
    prompt: enter your trainer name

  tasks:
  - name: prompt
    ansible.builtin.debug:
      msg: "course is {{COURSE}}, duration is {{DURATION}}, trainer is {{TRAINER}}"