- name: variables
  hosts: local
  connection: local
  vars:
    GREET: "Hello from play level variables"
  
  vars_files:
    variables_files.yaml
  
  vars_prompt:
    name: GREET
    prompt: please enter the value
    private: false

  # tasks:       #####2222222222222
  # - name: task level variables
  #   vars:
  #   - GREET: "task level variables"
  #   ansible.builtin.debug:
  #     msg: "print {{ GREET }}"