- name: data types
  hosts: local
  connection: local
  vars:
    COURSE: "devops with aws"  # String
    DURATION: 120  #Number
    topics:   # List
    - devops
    - aws
    - cloud
    - jenkins
    live: true   # Boolean
    tools:     # Map
      aws: devops
      shell: cloud
      jenkins: ci/cd
  
  tasks:
  - name: Print course information
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ DURATION }}, topics are {{ topics }} is it live {{ live }}, tools are {{ tools }}"

