- name: variables
  hosts: local
  connection: local
  vars:     # Play level variables     ##### 
    GREET: "play level variables"
  
  vars_files:   # variable files        
  - variables_files.yaml

  vars_prompt:       ###### 
  - name: GREET
    prompt: enter the value
    private: no

  tasks:          # Task level variables
  - name: task level variables
    # vars:
    #   GREET: "Task level variables"   ## 111111111111111
    ansible.builtin.debug:
      msg: "Hello from {{GREET}}"

  
  

