- name: convert string to list
  hosts: local
  connection: local
  tasks:
  - name: convert string to list
    vars:
      fruits: "goa, banana, apple"
    ansible.builtin.debug:
      msg: "fruits are {{ fruits | split(',') }}"

  - name: convert map to list
    vars:
      fruits:
        fruit1: goa
        fruit2: apple
        fruit3: banana
    ansible.builtin.debug:
      msg: "fruits are {{ fruits | dict2items }}"

  - name: Convert list to map in Ansible
    vars:
      fruit_pairs:
      - ["key1", "apple"]
      - ["key2", "banana"]
      - ["key3", "cherry"]
    ansible.builtin.debug:
      msg: "Converted map: {{ fruit_pairs | dict }}"