- name: convert string to list
  hosts: local
  connection: local
  tasks:
  - name: convert string to list
    vars:
      fruits: "goa, banana, apple"
    ansible.builtin.debug:
      msg: "fruits are {{ fruits | split(',') }}"

  - name: convert map to list
    vars:
      fruits:
        fruit1: goa
        fruit2: apple
        fruit3: banana
    ansible.builtin.debug:
      msg: "fruits are {{ fruits | dict2items }}"

  - name: Convert list to map
    vars:
      fruits:
      - { 'key': 'fruit1', 'value':'goa'}
      - { 'key': 'fruit2', 'value': 'banana'}
      - { 'key': 'fruit3', 'value': 'apple'}
    ansible.builtin.debug:
      msg: "fruits are {{ fruits | items2dict }}"
