- name: shell vs command module
  hosts: local
  connection: local
  tasks:
  - name: execute ls -ltr command
    ansible.builtin.command:  ls -l
    register: command_result

  - name: print output
    ansible.builtin.debug:
      msg: "{{ command_result }}"