- name: shell vs command module
  hosts: local
  connection: local
  tasks:
  - name: execute ls -ltr command
    ansible.builtin.command:  ls
    register: command_result

  - name: print output
    ansible.builtin.debug:
      msg: "{{ command_result }}" 

  - name: execute ls command
    ansible.builtin.shell: ls > /tmp/output.shell
    register: command_result

  - name: print the output  
    ansible.builtin.debug:
      msg: "{{ command_result }}"