- name: shell vs command module
  hosts: local
  connection: local
  tasks:
  - name: execute ls -ltr command
    ansible.builtin.command:  ls -ltr
    register: command_result

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ command_result }}"

  - name: execute and store output
    ansible.builtin.shell: ls -ltr > /tmp/outputtt
    register: command_result

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ command_result }}"
    
  


   