- name: loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install multiple packages
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    
    loop:
    - { name: 'git', state: 'installed' }
    - { name: 'zip', state: "absent" }
    - { name: 'nginx', state: installed }