- name: ansible facts
  hosts: node
  tasks:
  - name: print ansible facts
    ansible.builtin.debug:
      msg: "{{ansible_facts}}"






- name: ansible facts
  hosts: local
  connection: local
  tasks:
  - name: print ansible facts
    ansible.builtin.debug:
      msg: "{{ansible_facts}}"     