- name: Install nginx
  hosts: node
  become: yes
  tasks:
  - name: Install nginx if RHEL
    ansible.builtin.package:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  

    


