- name: loops ( Install Multiple packages )
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{item}}"
    loop:
    - ram
    - sita
    - anji