- name: Install Multiple packages using loops
  hosts: node
  become: yes
  tasks:
  - name: Install packages
    ansible.builtin.package:
      name: "{{item}}"
      state: absent
    loop:
    - gcc
    - zip
    - mysql