- name: Install and remove some packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Install and remove multiple packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'git', state: 'installed' }
    - { name: 'gcc', state: 'absent' }
    - { name: 'mysql', state: 'installed' }
    - { name: 'zip', state: 'absent' }

    