- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variable
    ansible.builtin.debug:
      msg: "hello from {{person | default('devops with aws') }}"

  tasks:
  - name: Convert string to list
    vars:
      fruits: "banana, goa, apple"
    ansible.builtin.debug:
      msg: "fruits are {{ fruits | split (',') }}"
