- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug:
      msg: "Hello from {{ person | default('ram') }}"

  - name: convert string to list
    vars:
      fruits: "banana, goa, apple"
    ansible.builtin.debug:
      msg: "fruits are {{ fruits | split(',') }}"