- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variable
    ansible.builtin.debug:
      msg: "hello from {{person | default('devops with aws') }}"

- name: convert String to list
  vars:
    fruits: "banana, goa, apple"
  ansible.builtin.debug:
    msg: "Fruits are: {{ fruits }} "