- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug:
      msg: "Hello from {{ person | default('ram') }}"

  - name: convert string to list
    vars:
      fruits: "banana, goa, apple"
    ansible.builtin.debug:
      msg: "fruits are {{ fruits | split(',') }}"

  - name: convert map into list
    vars:
      course:
        aws: devops
        shell: linux
        jenkins: cicd
    ansible.builtin.debug:
      msg: "course info {{ course | dict2items }} "

  - name: coonvert list into map
    vars:
      topics:
      - {'key': 'aws', 'value': 'devops'}
      - {'key': 'shell', 'value': 'linux'}
      - {'key': 'jenkins', 'value': 'cicd'}
    ansible.builtin.debug:
      msg: " topics are {{ topics | items2dict }}"