- name: create 3 ec2 instances and route 53 Records
  connection : local
  hosts: local
  vars:
    subnet_id: subnet-02ccdf4e5bf2d336e
    sg_id: sg-0748e2ac8f07844a2
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: Install aws python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
    register: ec2_info

  - name: print ec2_info
    ansible.builtin.debug:
      msg: "{{ ec2_info }}"

  - name: print private ip addresses
    ansible.builtin.debug:
    loop: "{{ ec2_info.results }}"