- name: variables
  hosts: local
  connection: local
  tasks:
  - name: print the variable
    ansible.builtin.module:
      msg: "course is devops with aws, duration is 120 hrs, trainer is sivakumar"