- name: Install and run apache
  hosts: ansible
  become: yes
  tasks:
  - name: Install apache
    ansible.builtin.package:
      name: httpd
      state: present
  - name: Start the apache service
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes
  
  - name: print a debug message
    ansible.builtin.debug:
      msg: "Apache is installed and running"