- name: Print Cloud course
  hosts: local
  connection: local
  vars:
    course_name: "Cloud course"  # String
    duration: 120   # Number
    topics:   #Here starting with Hyfen so it is "#List"
      - aws
      - cloud
      - jenkins
    live: true   #Boolean
    tools:    # Map
      aws: cloud
      jenkins: ci/cd
  tasks:
  - name: print cloud course information
    ansible.builtin.debug:
      msg: "hello i'm learning {{course_name}}, duration {{duration}}, topics are {{topics}}, is it live {{live}}, tools are {{tools}}"
  