- name: convert string to list
  hosts: local
  connection: local
  tasks:
  - name: convert string in to list
    vars:
      students: "ram, sita, anji"
    ansible.builtin.debug:
      msg: "students are {{ students | split(',') }}"
