# students: "ram, sita, anji"   #### STRING   [ ] --> this is list in output
 

- name: convert string to list
  hosts: local
  connection: local
  tasks:
  - name: convert string in to list
    vars:
      students: "ram, sita, anji"
    ansible.builtin.debug:
      msg: "students are {{ students | split(',') }}"

  - name: convert list to string
    vars:
      tools:
      - aws
      - linux
      - shell
    ansible.builtin.debug:
      msg: "tools are {{ tools | join(',') }}"
